name: Docker CI
on:
  push:
    paths:
      - 'Dockerfile'
      - 'entrypoint.sh'
  workflow_dispatch:

env:
  DOCKER_BUILDKIT: 1
  owner: chenchongbiao

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build dockerpi:vm
        run: docker build -t ${{ env.owner }}/dockerpi:vm --target dockerpi-vm .
      - name: Build dockerpi
        run: docker build -t ${{ env.owner }}/dockerpi:latest --target dockerpi .

  publish:
    name: Publish
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push to Docker Hub
        run: docker push --all-tags ${{ env.owner }}/dockerpi
